version: '3.8'

services:

  pavlov-1:
    image: aysen:1.0
    container_name: pavlov-1
    tty: true                                         
    user: root                                        

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy                       
    depends_on:
      - pavlov-1                                 
    ports:
      - "80:8080"                                     
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro   
    tty: true                                         
    user: root                                        